### ISSUE TITLE
TypeError: forward() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by mokzheen** [yanglan0225/s3net#1]
![image](https://user-images.githubusercontent.com/66867864/100035866-a87d6f00-2e31-11eb-93c7-104fe5c6040b.png)

Hi may i know how can I solve this bug? thanks !

**Comment by yanglan0225** [comment]
This is a Pytorch-geometric version problem. 
your version is  higher than 1.3.  after 1.3, they change the forward params, just delete self.add_loop is ok.

like : self.bn(1, F.relu(self.conv1(x0, adj, mask)))

**Comment by yanglan0225** [comment]
> This is a Pytorch-geometric version problem.
> your version is higher than 1.3. after 1.3, they change the forward params, just delete self.add_loop is ok.
> 
> like : self.bn(1, F.relu(self.conv1(x0, adj, mask)))

Refer to this website： https://github.com/rusty1s/pytorch_geometric/blob/a8a9031949fccda71a7e4fbbad7f60b0bef6765d/torch_geometric/nn/dense/dense_sage_conv.py#L6

**Comment by mokzheen** [comment]
ya removing this solves the bug, thanks a lot!
